export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS as `0x${string}`;

export const ABI = [
  {
    "type": "function",
    "name": "createOffer",
    "inputs": [
      {"name":"basePriceWeiPerKWh","type":"uint256"},
      {"name":"totalKWh","type":"uint256"}
    ],
    "outputs":[{"name":"offerId","type":"uint256"}],
    "stateMutability":"nonpayable"
  },
  {
    "type":"function",
    "name":"setOfferStatus",
    "inputs":[{"name":"offerId","type":"uint256"},{"name":"active","type":"bool"}],
    "outputs":[],
    "stateMutability":"nonpayable"
  },
  {
    "type":"function",
    "name":"updateOffer",
    "inputs":[
      {"name":"offerId","type":"uint256"},
      {"name":"newBasePriceWeiPerKWh","type":"uint256"},
      {"name":"newAvailableKWh","type":"uint256"}
    ],
    "outputs":[],
    "stateMutability":"nonpayable"
  },
  {
    "type":"function",
    "name":"offers",
    "inputs":[{"name":"offerId","type":"uint256"}],
    "outputs":[
      {"name":"seller","type":"address"},
      {"name":"basePriceWeiPerKWh","type":"uint256"},
      {"name":"availableKWh","type":"uint256"},
      {"name":"active","type":"bool"}
    ],
    "stateMutability":"view"
  },
  {
    "type":"function",
    "name":"buyEnergy",
    "inputs":[
      {"name":"offerId","type":"uint256"},
      {"name":"kWh","type":"uint256"},
      {"name":"weatherFactorBps","type":"uint256"},
      {"name":"weatherDesc","type":"string"},
      {"name":"latE6","type":"int256"},
      {"name":"lonE6","type":"int256"},
      {"name":"cloudPercent","type":"uint256"}
    ],
    "outputs":[],
    "stateMutability":"payable"
  },
  {
    "type":"function",
    "name":"nextOfferId",
    "inputs":[],
    "outputs":[{"type":"uint256"}],
    "stateMutability":"view"
  },
  {
    "type":"event",
    "name":"OfferCreated",
    "inputs":[
      {"name":"offerId","type":"uint256","indexed":true},
      {"name":"seller","type":"address","indexed":true},
      {"name":"basePriceWeiPerKWh","type":"uint256","indexed":false},
      {"name":"availableKWh","type":"uint256","indexed":false}
    ],
    "anonymous":false
  },
  {
    "type":"event",
    "name":"EnergyPurchased",
    "inputs":[
      {"name":"offerId","type":"uint256","indexed":true},
      {"name":"buyer","type":"address","indexed":true},
      {"name":"kWh","type":"uint256"},
      {"name":"pricePaidWei","type":"uint256"},
      {"name":"weatherFactorBps","type":"uint256"},
      {"name":"weatherDesc","type":"string"},
      {"name":"latE6","type":"int256"},
      {"name":"lonE6","type":"int256"},
      {"name":"cloudPercent","type":"uint256"}
    ],
    "anonymous":false
  }
] as const;
